const GAME_SETTINGS_ADULT_CONTENT_SWITCH_INPUT_ID = "game-settings-adult-content-switch-input";

const GAME_SETTINGS_ADULT_CONTENT_SWITCH_DESCRIPTION_ID = "game-settings-adult-content-description";

export { GAME_SETTINGS_ADULT_CONTENT_SWITCH_DESCRIPTION_ID, GAME_SETTINGS_ADULT_CONTENT_SWITCH_INPUT_ID };