# General
sonar.organization=antoinezanardi
sonar.projectKey=antoinezanardi_goat-it-web-game
sonar.projectDescription=Web game for the Goat It app.
sonar.links.homepage=https://github.com/antoinezanardi/goat-it-web-game
sonar.links.ci=https://github.com/antoinezanardi/goat-it-web-game/actions
sonar.links.issue=https://github.com/antoinezanardi/goat-it-web-game/issues
sonar.links.scm=https://github.com/antoinezanardi/goat-it-web-game

# Sources
sonar.sources=\
  app/,\
  server/,\
  shared/
sonar.exclusions=\
  node_modules/**/*,\
  dist/**/*,\
  **/*.spec.ts,\
  app/plugins/**/*

# Tests
sonar.tests=\
  app/,\
  server/,\
  shared/
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=tests/unit/coverage/lcov.info

# Coverage
sonar.coverage.exclusions=\
  nuxt.config.ts,\
  **/*.constants.ts,\
  **/*.types.ts,\
  **/*.enums.ts,\
  app/plugins/**/*,\
  server/api/**/*.{get,post,put,delete}.ts

# Duplication
sonar.cpd.exclusions=\
  **/*.constants.ts,\
  **/*.json

# Encodings
sonar.sourceEncoding=UTF-8