const CARD_TRANSITION_SLIDE_PERCENT = 100;

const CARD_TRANSITION_ROTATION_DEGREES = 6;

const CARD_TRANSITION_DURATION_SECONDS = 0.4;

const CARD_TRANSITION_SAFETY_MARGIN_MS = 200;

const MILLISECONDS_PER_SECOND = 1000;

const CARD_TRANSITION_SAFETY_TIMEOUT_MS = CARD_TRANSITION_DURATION_SECONDS * MILLISECONDS_PER_SECOND + CARD_TRANSITION_SAFETY_MARGIN_MS;

export { CARD_TRANSITION_DURATION_SECONDS, CARD_TRANSITION_ROTATION_DEGREES, CARD_TRANSITION_SAFETY_TIMEOUT_MS, CARD_TRANSITION_SLIDE_PERCENT };