export default {
  cleanTempDir: "always",
  incremental: true,
  incrementalFile: "tests/mutation/incremental/incremental.json",
  tsconfigFile: "tsconfig.json",
  testRunner: "vitest",
  ignoreStatic: true,
  mutate: [
    "**/*.mappers.ts",
    "**/*.helpers.ts",
    "**/*.repository.ts",
    "**/*.store.ts",
    "app/composables/**/*.ts",
    "!**/*.config.ts",
    "!**/*.constants.ts",
    "!**/*.d.ts",
    "!**/*.types.ts",
    "!**/*.spec.ts",
    "!tests/**/*.ts",
  ],
  plugins: ["@stryker-mutator/vitest-runner"],
  ignorePatterns: [
    "!.nuxt/",
    ".github/",
    ".husky/",
    ".output",
    ".opencode",
    ".agents",
    ".run/",
    ".idea/",
    "dist",
    "configs/commitlint",
    "configs/cucumber",
    "configs/eslint",
    "configs/lint-staged",
    "configs/stryker",
    "configs/node",
    "tests/acceptance",
    "tests/mutation",
    "tests/unit/coverage",
    "scripts/",
    ".editorconfig",
    ".npmrc",
    ".nvmrc",
    "release.config.mjs",
    ".DS_Store",
    ".validate-branch-namerc.json",
    "CHANGELOG.md",
    "LICENSE",
    "pnpm-lock.yaml",
    "sonar-project.properties",
    "README.md",
    ".coderabbit.yaml",
  ],
  concurrency: 2,
  vitest: { configFile: "configs/vitest/vitest-stryker.config.ts" },
  reporters: ["clear-text", "progress", "html", "json"],
  htmlReporter: { fileName: "tests/mutation/coverage/index.html" },
  jsonReporter: { fileName: "tests/mutation/coverage/mutation.json" },
  thresholds: {
    high: 100,
    low: 100,
    break: 100,
  },
  dryRunTimeoutMinutes: 10,
  warnings: {
    slow: false,
  },
};