const GAME_SETTINGS_COGNITIVE_DIFFICULTIES_LABEL_KEY = "game.settings.cognitiveDifficulties.label";

const GAME_SETTINGS_COGNITIVE_DIFFICULTIES_ALL_SELECTED_KEY = "game.settings.cognitiveDifficulties.allSelected";

const GAME_SETTINGS_COGNITIVE_DIFFICULTIES_OPTIONS_KEY_PREFIX = "game.settings.cognitiveDifficulties.options";

export {
  GAME_SETTINGS_COGNITIVE_DIFFICULTIES_ALL_SELECTED_KEY,
  GAME_SETTINGS_COGNITIVE_DIFFICULTIES_LABEL_KEY,
  GAME_SETTINGS_COGNITIVE_DIFFICULTIES_OPTIONS_KEY_PREFIX,
};