const GAME_SETTINGS_FILTER_MULTI_SELECT_SEARCH_PLACEHOLDER_KEY = "game.settings.filters.searchPlaceholder";

const GAME_SETTINGS_FILTER_MULTI_SELECT_SELECTED_COUNT_KEY = "game.settings.filters.selectedCount";

const GAME_SETTINGS_FILTER_MULTI_SELECT_CONFIRM_TITLE_KEY = "game.settings.filters.confirmRestoreTitle";

const GAME_SETTINGS_FILTER_MULTI_SELECT_CONFIRM_DESCRIPTION_KEY = "game.settings.filters.confirmRestoreDescription";

const GAME_SETTINGS_FILTER_MULTI_SELECT_CONFIRM_ACTION_KEY = "game.settings.filters.confirmRestoreAction";

const GAME_SETTINGS_FILTER_MULTI_SELECT_KEEP_ACTION_KEY = "game.settings.filters.keepSelectionAction";

const GAME_SETTINGS_FILTER_MULTI_SELECT_CONFIRM_ICON = "i-lucide-list-checks";

export {
  GAME_SETTINGS_FILTER_MULTI_SELECT_CONFIRM_ACTION_KEY,
  GAME_SETTINGS_FILTER_MULTI_SELECT_CONFIRM_DESCRIPTION_KEY,
  GAME_SETTINGS_FILTER_MULTI_SELECT_CONFIRM_ICON,
  GAME_SETTINGS_FILTER_MULTI_SELECT_CONFIRM_TITLE_KEY,
  GAME_SETTINGS_FILTER_MULTI_SELECT_KEEP_ACTION_KEY,
  GAME_SETTINGS_FILTER_MULTI_SELECT_SEARCH_PLACEHOLDER_KEY,
  GAME_SETTINGS_FILTER_MULTI_SELECT_SELECTED_COUNT_KEY,
};