const QUESTION_CARD_RING_RADIUS = 1;
const QUESTION_CARD_RING_DIAMETER_OFFSET = 2;
const QUESTION_CARD_RING_SIZE = QUESTION_CARD_RING_RADIUS * QUESTION_CARD_RING_DIAMETER_OFFSET + 1;

export { QUESTION_CARD_RING_RADIUS, QUESTION_CARD_RING_SIZE };