const QUESTION_CARD_HIGHLIGHT_DURATION_SECONDS = 0.6;
const QUESTION_CARD_HIGHLIGHT_STAGGER_SECONDS = 0.15;
const QUESTION_CARD_HIGHLIGHT_KEYFRAME_DURATION_SECONDS = 0.2;
const QUESTION_CARD_HIGHLIGHT_SCALE_BRIGHTNESS_KEYFRAMES = [
  { scale: 1.18, filter: "brightness(1.6)", duration: QUESTION_CARD_HIGHLIGHT_KEYFRAME_DURATION_SECONDS },
  { scale: 0.96, filter: "brightness(1.1)", duration: QUESTION_CARD_HIGHLIGHT_KEYFRAME_DURATION_SECONDS },
  { scale: 1, filter: "brightness(1)", duration: QUESTION_CARD_HIGHLIGHT_KEYFRAME_DURATION_SECONDS },
] as const;

export {
  QUESTION_CARD_HIGHLIGHT_DURATION_SECONDS,
  QUESTION_CARD_HIGHLIGHT_KEYFRAME_DURATION_SECONDS,
  QUESTION_CARD_HIGHLIGHT_SCALE_BRIGHTNESS_KEYFRAMES,
  QUESTION_CARD_HIGHLIGHT_STAGGER_SECONDS,
};