name: Docker Build 🐳
description: Build Dockerfile with specified platform.
author: Antoine ZANARDI

inputs:
  platform:
    description: Target platform for the Docker build (e.g., linux/amd64, linux/arm64)
    required: true

runs:
    using: composite
    steps:
      - name: Set up QEMU 🏗️
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx 🏗️
        uses: docker/setup-buildx-action@v4

      - name: Validate platform input 🚢
        id: validate-platform
        shell: bash
        run: |
          if [[ "${{ inputs.platform }}" != "linux/amd64" && "${{ inputs.platform }}" != "linux/arm64" ]]; then
            echo "Error: Invalid platform '${{ inputs.platform }}'. Supported platforms are 'linux/amd64' and 'linux/arm64'."
            exit 1
          fi

      - name: Docker Build 🐳
        id: docker-build
        shell: bash
        run: |
          docker buildx build \
            --platform ${{ inputs.platform }} \
            --build-arg NUXT_PUBLIC_SITE_URL="$NUXT_PUBLIC_SITE_URL" \
            --build-arg NUXT_PUBLIC_DEFAULT_LOCALE="$NUXT_PUBLIC_DEFAULT_LOCALE" \
            --secret id=goat_it_api_base_url,env=NUXT_GOAT_IT_API_BASE_URL \
            --secret id=goat_it_api_game_key,env=NUXT_GOAT_IT_API_GAME_KEY \
            --secret id=goat_it_og_image_security_secret,env=NUXT_OG_IMAGE_SECURITY_SECRET \
            -t goat-it-web-game .
