#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# clean-pr-description.sh
#
# Removes numbered diffhunk links from a pull request description.
# These links are in the format [[1]](diffhunk://...) or [[2]](diffhunk://...)
# and can clutter PR summaries generated by GitHub Copilot.
#
# Usage:
#   ./clean-pr-description.sh <pr-number>
#
# Arguments:
#   pr-number: The pull request number to clean
#
# Environment variables:
#   GITHUB_TOKEN: GitHub token for authentication (required)
#   GITHUB_REPOSITORY: Repository in the format owner/repo (required)
# -----------------------------------------------------------------------------

set -euo pipefail
IFS=$'\n\t'

# Check required commands
command -v gh >/dev/null 2>&1 || { echo "❌  gh (GitHub CLI) is required." >&2; exit 1; }

# Check required environment variables
if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "❌  GITHUB_TOKEN environment variable is required." >&2
  exit 1
fi

if [[ -z "${GITHUB_REPOSITORY:-}" ]]; then
  echo "❌  GITHUB_REPOSITORY environment variable is required." >&2
  exit 1
fi

# Check arguments
if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <pr-number>" >&2
  exit 1
fi

PR_NUMBER="$1"

# Validate PR number is a positive integer
if ! [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
  echo "❌  PR number must be a positive integer." >&2
  exit 1
fi

echo "🔍  Fetching PR #$PR_NUMBER description..."

# Get current PR description
CURRENT_DESCRIPTION=$(gh pr view "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --json body --jq '.body')

if [[ -z "$CURRENT_DESCRIPTION" || "$CURRENT_DESCRIPTION" == "null" ]]; then
  echo "⚠️  PR #$PR_NUMBER has no description. Nothing to clean."
  exit 0
fi

# Remove numbered diffhunk links using sed
# Pattern matches: [[1]](diffhunk://...), [[2]](diffhunk://...), etc.
# The pattern is: \[\[[0-9]+\]\]\(diffhunk://[^)]+\)
# Then use awk to remove trailing spaces from each line and collapse multiple spaces
CLEANED_DESCRIPTION=$(echo "$CURRENT_DESCRIPTION" | sed -E 's/\[\[[0-9]+\]\]\(diffhunk:\/\/[^)]+\)//g' | awk '{gsub(/  +/, " "); sub(/[[:space:]]+$/, ""); print}')

# Check if the description was modified
if [[ "$CURRENT_DESCRIPTION" == "$CLEANED_DESCRIPTION" ]]; then
  echo "✅  PR #$PR_NUMBER description is already clean. No changes needed."
  exit 0
fi

echo "🧹  Cleaning PR #$PR_NUMBER description..."

# Update PR description
# We need to create a temporary file because gh pr edit reads from stdin or a file
TEMP_FILE=$(mktemp)
trap 'rm -f "$TEMP_FILE"' EXIT

printf '%s\n' "$CLEANED_DESCRIPTION" > "$TEMP_FILE"

gh pr edit "$PR_NUMBER" --repo "$GITHUB_REPOSITORY" --body-file "$TEMP_FILE"

echo "✅  Successfully cleaned PR #$PR_NUMBER description."
