const GAME_TUTORIAL_INVITATION_TOAST_ID = "game-tutorial-invitation";

const GAME_TUTORIAL_INVITATION_DECISION_COOKIE_MAX_AGE_IN_SECONDS = 34_560_000;

const GAME_TUTORIAL_INVITATION_DECISION_COOKIE_OPTIONS = {
  path: "/",
  maxAge: GAME_TUTORIAL_INVITATION_DECISION_COOKIE_MAX_AGE_IN_SECONDS,
  sameSite: "lax",
} as const;

export {
  GAME_TUTORIAL_INVITATION_DECISION_COOKIE_MAX_AGE_IN_SECONDS,
  GAME_TUTORIAL_INVITATION_DECISION_COOKIE_OPTIONS,
  GAME_TUTORIAL_INVITATION_TOAST_ID,
};