const BEFORE_ALL_TIMEOUT = 360_000;

const BEFORE_TIMEOUT = 60_000;

const ACCEPTANCE_TESTS_DEFAULT_LOCALE = "en";

const SANDBOX_BASE_PORT = 9090;

const SANDBOX_ADMIN_KEY = "test_admin_api_key_for_testing";

const SANDBOX_HEALTH_CHECK_MAX_RETRIES = 10;

const SANDBOX_HEALTH_CHECK_INTERVAL_IN_MS = 2000;

const SANDBOX_MONGODB_DATABASE_NAME = "goat-it-sandbox";

const RESET_SANDBOX_DATA_TIMEOUT_IN_MS = 10_000;

const SHARED_BUILD_DIR = ".nuxt/test";

export {
  ACCEPTANCE_TESTS_DEFAULT_LOCALE,
  BEFORE_ALL_TIMEOUT,
  BEFORE_TIMEOUT,
  RESET_SANDBOX_DATA_TIMEOUT_IN_MS,
  SANDBOX_ADMIN_KEY,
  SANDBOX_BASE_PORT,
  SANDBOX_HEALTH_CHECK_INTERVAL_IN_MS,
  SANDBOX_HEALTH_CHECK_MAX_RETRIES,
  SANDBOX_MONGODB_DATABASE_NAME,
  SHARED_BUILD_DIR,
};