const AFTER_ALL_TIMEOUT = 60_000;

const BEFORE_ALL_TIMEOUT = 360_000;

const BEFORE_TIMEOUT = 60_000;

const ACCEPTANCE_TESTS_DEFAULT_LOCALE = "en";

const SANDBOX_BASE_PORT = 9090;

const ACCEPTANCE_TESTS_SITE_URL = "https://test.goat-it.fr";

const ACCEPTANCE_TESTS_OG_IMAGE_SECURITY_SECRET = "test_og_image_security_secret";

const SANDBOX_GAME_KEY = "test_game_api_key_for_testing";

const SANDBOX_HEALTH_CHECK_MAX_RETRIES = 10;

const SANDBOX_HEALTH_CHECK_INTERVAL_IN_MS = 2000;

const SANDBOX_MONGODB_DATABASE_NAME = "goat-it-sandbox";

const SANDBOX_MONGODB_PORT_BASE = 27_117;

const RESET_SANDBOX_DATA_TIMEOUT_IN_MS = 30_000;

const SHARED_BUILD_DIR = ".nuxt/test";

export {
  ACCEPTANCE_TESTS_DEFAULT_LOCALE,
  ACCEPTANCE_TESTS_OG_IMAGE_SECURITY_SECRET,
  ACCEPTANCE_TESTS_SITE_URL,
  AFTER_ALL_TIMEOUT,
  BEFORE_ALL_TIMEOUT,
  BEFORE_TIMEOUT,
  RESET_SANDBOX_DATA_TIMEOUT_IN_MS,
  SANDBOX_BASE_PORT,
  SANDBOX_GAME_KEY,
  SANDBOX_HEALTH_CHECK_INTERVAL_IN_MS,
  SANDBOX_HEALTH_CHECK_MAX_RETRIES,
  SANDBOX_MONGODB_DATABASE_NAME,
  SANDBOX_MONGODB_PORT_BASE,
  SHARED_BUILD_DIR,
};