name: ⚙️ Build Workflow
on:
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  code-ql:
    name: CodeQL Scan ❇️
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository 📡
        uses: actions/checkout@v7

      - name: Perform CodeQL Analysis ❇️
        uses: ./.github/actions/code-ql

  lint-workflows:
    name: Lint GitHub Workflows 🐙
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v7

      - name: Create dummy package.json for ActionLint 📄
        run: |
          echo '{
            "name": "dummy-package",
            "version": "1.0.0",
            "private": true
          }' > package.json

      - name: Lint GitHub Workflows 🐙
        uses: raven-actions/actionlint@v2.2.0
        with:
          matcher: true
          fail-on-error: true
          shellcheck: true
          pyflakes: true
          cache: true
          group-result: true

  install:
    name: Install ⚙️
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v7

      - name: Install project 📦
        uses: ./.github/actions/install-project

  docker-builds:
    name: Docker Build 🐳
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        platform: ["linux/amd64", "linux/arm64"]
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v7

      - name: Docker Build 🐳
        uses: ./.github/actions/docker-build
        with:
          platform: ${{ matrix.platform }}

  build:
    name: Build App ✨
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - install
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v7

      - name: Build application ✨
        uses: ./.github/actions/build

  lint-codebase:
    name: Lint Codebase 🔍
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - install
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v7

      - name: Lint Codebase 🔍
        id: lint-codebase
        uses: ./.github/actions/lint

  unit-tests:
    name: Unit Tests 🧪
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - install
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v7

      - name: Unit Tests 🧪
        id: unit-tests
        uses: ./.github/actions/unit-tests

  acceptance-tests:
    name: Acceptance Tests 🥒
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - install
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v7

      - name: Acceptance Tests 🥒
        id: acceptance-tests
        uses: ./.github/actions/acceptance-tests

  sonarcloud:
    name: SonarCloud Analysis 🌥️
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
    needs:
      - unit-tests
    if: github.actor != 'renovate[bot]'
    steps:
      - name: Checkout GitHub repository 📡
        uses: actions/checkout@v7

      - name: SonarCloud Analysis 🌥️
        uses: ./.github/actions/sonarcloud
        with:
          sonarcloud-token: ${{ secrets.SONARCLOUD_TOKEN }}
